### ISSUE TITLE
OAuth periodically doesn't produce a functioning token

### ISSUE THREAD

**Issue by mikejgray** [OpenVoiceOS/ovos-PHAL-plugin-homeassistant#46]
```bash
2023-09-27 08:59:08.372 - enclosure - ovos_phal_plugin_connectivity_events:update_state:82 - INFO - Network state changed to: NONE
2023-09-27 09:00:08.969 - enclosure - ovos_phal_plugin_connectivity_events:update_state:82 - INFO - Network state changed to: FULL
2023-09-27 09:00:12.347 - enclosure - neon_phal_plugin_gui_network_client:request_deactivate:109 - INFO - Gui Network Client Plugin Deactivation Requested
2023-09-27 17:34:19.556 - enclosure - ovos_utils.gui:_normalize_page_name:835 - WARNING - Deprecation version=0.1.0. Caller=ovos_PHAL_plugin_homeassistant:654. GUI resources should specify a resource name and not a file path.
2023-09-27 17:36:17.576 - enclosure - ovos_PHAL_plugin_homeassistant.logic.socketclient:_connect:64 - ERROR - sent 1000 (OK); then received 1000 (OK)
Traceback (most recent call last):
File "/home/neon/venv/lib/python3.10/site-packages/ovos_PHAL_plugin_homeassistant/logic/[socketclient.py](http://socketclient.py/)", line 58, in _connect
await self.authenticate()
File "/home/neon/venv/lib/python3.10/site-packages/ovos_PHAL_plugin_homeassistant/logic/[socketclient.py](http://socketclient.py/)", line 39, in authenticate
await self.listen()
File "/home/neon/venv/lib/python3.10/site-packages/ovos_PHAL_plugin_homeassistant/logic/[socketclient.py](http://socketclient.py/)", line 75, in listen
message = await self.websocket.recv()
File "/home/neon/venv/lib/python3.10/site-packages/websockets/legacy/[protocol.py](http://protocol.py/)", line 568, in recv
await self.ensure_open()
File "/home/neon/venv/lib/python3.10/site-packages/websockets/legacy/[protocol.py](http://protocol.py/)", line 953, in ensure_open
raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: sent 1000 (OK); then received 1000 (OK)
2023-09-27 17:36:17.587 - enclosure - ovos_PHAL_plugin_homeassistant.logic.socketclient:run:246 - INFO - [self.loop.is](http://self.loop.is/)_running=False
2023-09-27 17:36:17.896 - enclosure - ovos_PHAL_plugin_homeassistant.logic.socketclient:_connect:64 - ERROR - sent 1000 (OK); then received 1000 (OK)
Traceback (most recent call last):
File "/home/neon/venv/lib/python3.10/site-packages/ovos_PHAL_plugin_homeassistant/logic/[socketclient.py](http://socketclient.py/)", line 58, in _connect
await self.authenticate()
File "/home/neon/venv/lib/python3.10/site-packages/ovos_PHAL_plugin_homeassistant/logic/[socketclient.py](http://socketclient.py/)", line 39, in authenticate
await self.listen()
File "/home/neon/venv/lib/python3.10/site-packages/ovos_PHAL_plugin_homeassistant/logic/[socketclient.py](http://socketclient.py/)", line 75, in listen
message = await self.websocket.recv()
File "/home/neon/venv/lib/python3.10/site-packages/websockets/legacy/[protocol.py](http://protocol.py/)", line 568, in recv
await self.ensure_open()
File "/home/neon/venv/lib/python3.10/site-packages/websockets/legacy/[protocol.py](http://protocol.py/)", line 953, in ensure_open
raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: sent 1000 (OK); then received 1000 (OK)
2023-09-27 17:36:17.900 - enclosure - ovos_PHAL_plugin_homeassistant.logic.socketclient:run:246 - INFO - [self.loop.is](http://self.loop.is/)_running=False
2023-09-27 17:36:19.226 - enclosure - ovos_utils.gui:_normalize_page_name:835 - WARNING - Deprecation version=0.1.0. Caller=ovos_PHAL_plugin_homeassistant:646. GUI resources should specify a resource name and not a file path.
2023-09-27 17:39:43.062 - enclosure - ovos_PHAL_plugin_homeassistant.logic.socketclient:_connect:64 - ERROR - sent 1000 (OK); then received 1000 (OK)
Traceback (most recent call last):
File "/home/neon/venv/lib/python3.10/site-packages/ovos_PHAL_plugin_homeassistant/logic/[socketclient.py](http://socketclient.py/)", line 58, in _connect
await self.authenticate()
File "/home/neon/venv/lib/python3.10/site-packages/ovos_PHAL_plugin_homeassistant/logic/[socketclient.py](http://socketclient.py/)", line 39, in authenticate
await self.listen()
File "/home/neon/venv/lib/python3.10/site-packages/ovos_PHAL_plugin_homeassistant/logic/[socketclient.py](http://socketclient.py/)", line 75, in listen
message = await self.websocket.recv()
File "/home/neon/venv/lib/python3.10/site-packages/websockets/legacy/[protocol.py](http://protocol.py/)", line 568, in recv
await self.ensure_open()
File "/home/neon/venv/lib/python3.10/site-packages/websockets/legacy/[protocol.py](http://protocol.py/)", line 944, in ensure_open
raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: sent 1000 (OK); then received 1000 (OK)
2023-09-27 17:39:43.075 - enclosure - ovos_PHAL_plugin_homeassistant.logic.socketclient:run:246 - INFO - [self.loop.is](http://self.loop.is/)_running=False
2023-09-27 17:39:43.357 - enclosure - ovos_PHAL_plugin_homeassistant.logic.socketclient:_connect:64 - ERROR - sent 1000 (OK); then received 1000 (OK)
Traceback (most recent call last):
File "/home/neon/venv/lib/python3.10/site-packages/ovos_PHAL_plugin_homeassistant/logic/[socketclient.py](http://socketclient.py/)", line 58, in _connect
await self.authenticate()
File "/home/neon/venv/lib/python3.10/site-packages/ovos_PHAL_plugin_homeassistant/logic/[socketclient.py](http://socketclient.py/)", line 39, in authenticate
await self.listen()
File "/home/neon/venv/lib/python3.10/site-packages/ovos_PHAL_plugin_homeassistant/logic/[socketclient.py](http://socketclient.py/)", line 75, in listen
message = await self.websocket.recv()
File "/home/neon/venv/lib/python3.10/site-packages/websockets/legacy/[protocol.py](http://protocol.py/)", line 568, in recv
await self.ensure_open()
File "/home/neon/venv/lib/python3.10/site-packages/websockets/legacy/[protocol.py](http://protocol.py/)", line 953, in ensure_open
raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: sent 1000 (OK); then received 1000 (OK)
2023-09-27 17:39:43.359 - enclosure - ovos_PHAL_plugin_homeassistant.logic.socketclient:run:246 - INFO - [self.loop.is](http://self.loop.is/)_running=False
2023-09-27 17:39:44.751 - enclosure - ovos_utils.gui:_normalize_page_name:835 - WARNING - Deprecation version=0.1.0. Caller=ovos_PHAL_plugin_homeassistant:646. GUI resources should specify a resource name and not a file path.
```

**Comment by mikejgray** [comment]
Duplicates #19 , so closing in favor of that
